### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by ParadiseN1** [WangWenhao0716/ISC-Track1-Submission#1]
Hi guys, congrats on taking first place! Are you planning to upload models weights? Seems like training with this setup is pretty expensive for ordinary people :)

**Comment by WangWenhao0716** [comment]
Thanks. In fact, all the weights have been uploaded. Please refer to the README file in each part.



发自我的iPhone


------------------ Original ------------------
From: Volodymyr Prypeshnyuk ***@***.***&gt;
Date: Thu,Nov 18,2021 5:35 PM
To: WangWenhao0716/ISC-Track1-Submission ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [WangWenhao0716/ISC-Track1-Submission] Pre-trained models (Issue #1)





 
Hi guys, congrats on taking first place! Are you planning to upload models weights? Seems like training with this setup is pretty expensive for ordinary people :)
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ParadiseN1** [comment]
@WangWenhao0716 You are right, idk how could I missed that while reading, much thanks!)
